import { useState, type ReactNode } from "react";
import { Link, useRouterState } from "@tanstack/react-router";
import { BarChart3, Bell, BriefcaseBusiness, Check, ChevronRight, CircleUserRound, FileText, FolderKanban, GraduationCap, LayoutDashboard, Menu, Moon, MoreHorizontal, Pencil, Plus, Search, Settings, Sparkles, Target, Upload, UserRound, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { activity, demoProfile, jobAnalysis, roadmap, skills } from "@/lib/mock-data";

export function Logo({ light = false }: { light?: boolean }) {
  return <Link to="/" className="flex items-center gap-2.5" aria-label="KARNA AI home"><span className={cn("grid size-8 place-items-center rounded-lg font-display text-sm font-bold", light ? "bg-paper text-ink" : "bg-ink text-paper")}>K</span><span className={cn("font-display text-base font-semibold tracking-tight", light ? "text-paper" : "text-foreground")}>KARNA AI</span></Link>;
}

const navItems = [
  { to: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { to: "/resume", label: "Resume Analyzer", icon: FileText },
  { to: "/jobs", label: "Job Matching", icon: BriefcaseBusiness },
  { to: "/skills", label: "Skill Gap", icon: BarChart3 },
  { to: "/roadmap", label: "Career Roadmap", icon: FolderKanban },
  { to: "/interview", label: "Interview Prep", icon: GraduationCap },
];

function NavLink({ to, label, icon: Icon, onNavigate }: { to: string; label: string; icon: typeof LayoutDashboard; onNavigate?: () => void }) {
  const pathname = useRouterState({ select: (state) => state.location.pathname });
  const active = pathname === to;
  return <Link to={to} onClick={onNavigate} className={cn("group flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition-colors", active ? "bg-sidebar-primary text-sidebar-primary-foreground" : "text-sidebar-foreground/65 hover:bg-sidebar-accent hover:text-sidebar-foreground")}><Icon className="size-4" /><span>{label}</span></Link>;
}

export function AppShell({ title, eyebrow, children }: { title: string; eyebrow?: string; children: ReactNode }) {
  const [open, setOpen] = useState(false);
  return <div className="min-h-screen bg-paper text-foreground">
    <aside className={cn("fixed inset-y-0 left-0 z-50 flex w-64 flex-col bg-sidebar px-4 py-5 transition-transform lg:translate-x-0", open ? "translate-x-0" : "-translate-x-full")}>
      <div className="flex items-center justify-between px-2"><Logo light /><Button variant="ghost" size="icon" className="text-sidebar-foreground/70 hover:bg-sidebar-accent hover:text-sidebar-foreground lg:hidden" aria-label="Close navigation" onClick={() => setOpen(false)}><X /></Button></div>
      <div className="mt-9 px-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-sidebar-foreground/35">Workspace</div>
      <nav className="mt-3 space-y-1">{navItems.map((item) => <NavLink key={item.to} {...item} onNavigate={() => setOpen(false)} />)}</nav>
      <div className="mt-8 px-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-sidebar-foreground/35">Account</div>
      <nav className="mt-3 space-y-1"><NavLink to="/profile" label="Profile" icon={UserRound} onNavigate={() => setOpen(false)} /><NavLink to="/settings" label="Settings" icon={Settings} onNavigate={() => setOpen(false)} /></nav>
      <div className="mt-auto rounded-xl border border-sidebar-border bg-sidebar-accent p-3"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-full bg-sidebar-primary text-xs font-semibold text-sidebar-primary-foreground">AK</span><div className="min-w-0"><p className="truncate text-xs font-medium text-sidebar-foreground">Alex Kumar</p><p className="truncate text-[10px] text-sidebar-foreground/45">Demo profile</p></div></div><div className="mt-3 flex items-center justify-between text-[10px] text-sidebar-foreground/55"><span>Roadmap progress</span><span>24%</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-sidebar-foreground/10"><div className="h-full w-[24%] rounded-full bg-sidebar-primary" /></div></div>
    </aside>
    {open && <button className="fixed inset-0 z-40 bg-ink/40 lg:hidden" aria-label="Close navigation overlay" onClick={() => setOpen(false)} />}
    <div className="lg:pl-64"><header className="sticky top-0 z-30 border-b border-line/70 bg-paper/85 backdrop-blur-xl"><div className="flex h-16 items-center justify-between gap-4 px-5 lg:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open navigation" onClick={() => setOpen(true)}><Menu /></Button><div className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex"><span className="text-muted-foreground/50">Workspace</span><ChevronRight className="size-3" /><span className="font-medium text-foreground">{title}</span></div><div className="sm:hidden"><span className="font-display font-semibold">{title}</span></div></div><div className="flex items-center gap-2"><div className="relative hidden w-56 md:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input placeholder="Search workspace" className="h-9 rounded-lg border-line bg-card pl-9 text-xs" aria-label="Search workspace" /></div><Button variant="ghost" size="icon" className="relative" aria-label="Notifications"><Bell className="size-4" /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-signal" /></Button><Button variant="ghost" size="icon" aria-label="Open profile"><CircleUserRound className="size-5" /></Button></div></div></header><main className="app-grid min-h-[calc(100vh-4rem)]"><div className="mx-auto max-w-[1320px] px-5 py-8 lg:px-8"><div className="mb-7"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-brand">{eyebrow ?? "Career intelligence"}</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h1></div>{children}</div></main></div>
  </div>;
}

export function MetricCard({ label, value, detail, icon: Icon, tone = "brand" }: { label: string; value: string; detail: string; icon: typeof Target; tone?: "brand" | "signal" | "warning" | "success" }) {
  const tones = { brand: "bg-brand/10 text-brand", signal: "bg-signal/15 text-info", warning: "bg-warning/15 text-warning", success: "bg-success/15 text-success" };
  return <div className="app-surface rounded-xl bg-card/75 p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></div><div className={cn("grid size-9 place-items-center rounded-lg", tones[tone])}><Icon className="size-4" /></div></div></div>;
}

export function ProgressRow({ name, value, accent = false }: { name: string; value: number; accent?: boolean }) { return <div><div className="flex items-center justify-between text-xs"><span className="font-medium">{name}</span><span className="text-muted-foreground">{value}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-ink/10"><div className={cn("animate-bar h-full rounded-full", accent ? "bg-signal" : "bg-brand")} style={{ width: `${value}%` }} /></div></div>; }

export function SectionHeader({ title, detail, action }: { title: string; detail?: string; action?: ReactNode }) { return <div className="flex items-end justify-between gap-4"><div><h2 className="font-display text-lg font-semibold tracking-tight">{title}</h2>{detail && <p className="mt-1 text-xs text-muted-foreground">{detail}</p>}</div>{action}</div>; }

export function StatusBadge({ status }: { status: string }) { const tone = status === "Strong" || status === "Completed" ? "bg-success/10 text-success border-success/20" : status === "Missing" || status === "High" ? "bg-warning/10 text-warning border-warning/20" : "bg-brand/10 text-brand border-brand/20"; return <Badge variant="outline" className={cn("rounded-full font-medium", tone)}>{status}</Badge>; }

export function LandingHeader() { return <header className="border-b border-line/80 bg-paper/75 backdrop-blur-sm"><div className="mx-auto flex max-w-[1200px] items-center justify-between px-5 py-4"><Logo /><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#features" className="transition-colors hover:text-foreground">Features</a><a href="#how-it-works" className="transition-colors hover:text-foreground">How it works</a><a href="#students" className="transition-colors hover:text-foreground">For students</a></nav><div className="flex items-center gap-2"><Button asChild variant="ghost" className="hidden text-muted-foreground sm:inline-flex"><Link to="/login">Sign in</Link></Button><Button asChild className="rounded-lg bg-brand text-primary-foreground hover:bg-brand-deep"><Link to="/register">Get Started <ChevronRight className="size-4" /></Link></Button></div></div></header>; }

export function DashboardPreview() { return <div className="relative"><div className="pointer-events-none absolute -left-16 -top-16 h-64 w-64 -skew-x-12 bg-signal/20 blur-3xl" /><div className="pointer-events-none absolute -bottom-20 -right-12 h-72 w-72 -skew-x-12 bg-brand/20 blur-3xl" /><div className="relative rounded-[18px] bg-card/45 p-2 shadow-2xl shadow-ink/15 ring-1 ring-ink/5 backdrop-blur-xl"><div className="rounded-[14px] bg-ink p-5 text-paper sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[11px] uppercase tracking-[0.14em] text-paper/45">Dashboard</p><p className="font-display text-lg font-semibold">Good morning, Alex</p></div><Badge className="rounded-full border border-signal/25 bg-signal/15 text-signal">● 78% aligned</Badge></div><div className="mt-5 grid grid-cols-3 gap-3">{[["Profile alignment", "78%", "+6 this week"], ["Skills", "14", "8 strong"], ["Skill gaps", "5", "2 high priority"]].map(([label, value, detail]) => <div key={label} className="rounded-xl bg-paper/5 p-3 ring-1 ring-paper/10"><p className="text-[11px] text-paper/50">{label}</p><p className="mt-1 font-display text-2xl font-semibold">{value}</p><p className="mt-0.5 text-[11px] text-signal/80">{detail}</p></div>)}</div><div className="mt-5 rounded-xl bg-paper/5 p-4 ring-1 ring-paper/10"><div className="flex items-center justify-between"><p className="text-xs font-medium text-paper/70">Skill progress</p><p className="text-[11px] text-paper/40">vs. ML Engineer</p></div><div className="mt-3 space-y-3">{skills.slice(0, 5).map((skill) => <div key={skill.name} className="flex items-center gap-3"><span className="w-28 shrink-0 truncate text-xs text-paper/70">{skill.name}</span><span className="h-1.5 flex-1 overflow-hidden rounded-full bg-paper/10"><span className={cn("animate-bar block h-full rounded-full", skill.level > 60 ? "bg-signal" : "bg-paper/40")} style={{ width: `${skill.level}%` }} /></span><span className="w-8 text-right text-[11px] text-paper/50">{skill.level}</span></div>)}</div></div></div></div><div className="absolute -bottom-5 -left-3 hidden items-center gap-2 rounded-xl bg-card/85 px-3 py-2 text-xs font-medium text-foreground shadow-lg ring-1 ring-ink/5 backdrop-blur-md sm:flex"><span className="grid size-5 place-items-center rounded-full bg-brand/10 text-brand"><Zap className="animate-signal size-3" /></span> Analyzing job description…</div></div>; }

export function ActivityList() { return <div className="space-y-4">{activity.map((item) => <div key={item.title} className="flex items-start gap-3"><span className={cn("mt-1 grid size-7 shrink-0 place-items-center rounded-full", item.tone === "success" ? "bg-success/10 text-success" : item.tone === "signal" ? "bg-signal/15 text-info" : item.tone === "brand" ? "bg-brand/10 text-brand" : "bg-info/10 text-info")}><Check className="size-3.5" /></span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.title}</p><p className="truncate text-xs text-muted-foreground">{item.detail}</p></div><span className="shrink-0 text-[10px] text-muted-foreground">{item.time}</span></div>)}</div>; }

export function QuickAction({ to, icon: Icon, title, detail }: { to: string; icon: typeof FileText; title: string; detail: string }) { return <Button asChild variant="outline" className="h-auto justify-start rounded-xl border-line bg-card/60 px-4 py-3 text-left hover:border-brand/40"><Link to={to}><span className="grid size-8 place-items-center rounded-lg bg-brand/10 text-brand"><Icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{title}</span><span className="mt-0.5 block truncate text-[11px] font-normal text-muted-foreground">{detail}</span></span><ChevronRight className="size-4 text-muted-foreground" /></Link></Button>; }

export function UploadPanel({ onUploaded }: { onUploaded: () => void }) { const [loading, setLoading] = useState(false); const handle = () => { setLoading(true); window.setTimeout(() => { setLoading(false); onUploaded(); }, 900); }; return <div className="app-surface rounded-2xl bg-card/75 p-6 sm:p-10"><div className="flex min-h-64 flex-col items-center justify-center rounded-xl border border-dashed border-brand/35 bg-brand/[0.03] px-5 text-center"><div className="grid size-14 place-items-center rounded-xl bg-brand/10 text-brand">{loading ? <Sparkles className="animate-signal" /> : <Upload />}</div><h2 className="mt-5 font-display text-xl font-semibold">{loading ? "Analyzing your resume…" : "Upload your resume"}</h2><p className="mt-2 max-w-sm text-sm text-muted-foreground">{loading ? "Extracting content, mapping skills, and generating insights." : "Upload a PDF to see your profile strengths, coverage, and next improvements."}</p><Button className="mt-6 rounded-lg bg-brand text-primary-foreground hover:bg-brand-deep" onClick={handle} disabled={loading}>{loading ? "Processing" : "Choose Resume"}</Button><p className="mt-3 text-[11px] text-muted-foreground">PDF · Demo upload only · Max 10 MB</p></div></div>; }

export function EmptyState({ icon: Icon = MoreHorizontal, title, detail, action }: { icon?: typeof MoreHorizontal; title: string; detail: string; action?: ReactNode }) { return <div className="app-surface flex min-h-56 flex-col items-center justify-center rounded-xl bg-card/65 p-6 text-center"><div className="grid size-11 place-items-center rounded-xl bg-muted text-muted-foreground"><Icon className="size-5" /></div><h3 className="mt-4 font-display font-semibold">{title}</h3><p className="mt-1 max-w-sm text-sm text-muted-foreground">{detail}</p>{action && <div className="mt-5">{action}</div>}</div>; }

export { demoProfile, jobAnalysis, roadmap, skills };